@host = http://localhost:8080/meja
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZF91c2VyIjo1LCJ1c2VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg5MDE0MzEsImV4cCI6MTY4MDU4MDMzMjcxOH0.rtGhL1Fv6M9osqwKLDHnEnKUQlPqk11kXW7RLC18kFw


### Token manager
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZF91c2VyIjo3LCJ1c2VybmFtZSI6Im1hbmFnZXIiLCJlbWFpbCI6Im1hbmFnZXJAZXhhbXBsZS5jb20iLCJyb2xlIjoibWFuYWdlciJ9LCJpYXQiOjE2Nzg5MDE2MzYsImV4cCI6MTY4MDU4MDUzODY2Mn0.a2JFT5uploOeE1zuqOttW4lq3BQpfGVg-pR1vSJBbec

### GET MEJA
GET  {{host}}/get HTTP/1.1
Authorization: Bearer {{token}}

### GET MEJA BY ID
GET  {{host}}/get/5 HTTP/1.1
Authorization: Bearer {{token}}

### INSERT MEJA
POST {{host}}/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":1,
    "status":"tersedia"
}


### EDIT MEJA ALL FIELDS
PUT {{host}}/edit/3 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":4,
    "status":"tersedia"
}

### EDIT MEJA
PUT {{host}}/edit/9 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":20,
    "status":"tidak_tersedia"
}

### EDIT STATUS MEJA
PUT {{host}}/edit-status/9 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":20,
    "status":"tersedia"
}


###DELETE MEJA BY NOMOR MEJA --NOTE
DELETE  {{host}}/delete/9 HTTP/1.1
Authorization: Bearer {{token}}
