### Register
POST http://localhost:8080/auth/registrasi HTTP/1.1
Content-Type: application/json

{
    "nama_user": "Admin", 
    "username": "Admin", 
    "email": "admin@example.com", 
    "password": "Password123#", 
    "confPassword": "Password123#"
}

### Login 
POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "apaaja@example.com", 
    "password": "Password123#"
}

### Logout
DELETE http://localhost:8080/auth/logout HTTP/1.1
Content-Type: application/json

### Refresh Token
GET http://localhost:8080/auth/token HTTP/1.1
Content-Type: application/json


### Ganti Email
POST http://localhost:8080/auth/reset-email/2 HTTP/1.1
Content-Type: application/json

{
    "email": "kasir@example.com"
}

### Ganti password
POST http://localhost:8080/auth/reset-password/7 HTTP/1.1
Content-Type: application/json

{
    "password_lama": "Password123#",
    "password_baru": "Password123#d"

}