@host = http://localhost:8080/meja
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZF91c2VyIjoxLCJ1c2VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg3NjE5OTcsImV4cCI6MTY4MDQ0MDc1OTYyMn0.qxyBz12lMciwixoIKXa0H8Zhd3hZOlJ4ON-yinmX9YI

### GET MEJA
GET  {{host}}/get HTTP/1.1
Authorization: Bearer {{token}}

### GET MEJA BY ID
GET  {{host}}/get/5 HTTP/1.1
Authorization: Bearer {{token}}


### INSERT MEJA
POST {{host}}/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":23,
    "status":"tersedia"
}


### EDIT MEJA ALL FIELDS
PUT {{host}}/edit/2 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":4,
    "status":"tersedia"
}


### EDIT MEJA
PUT {{host}}/edit/3 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":23,
    "status":"tidak_tersedia"
}

### EDIT STATUS MEJA
PUT {{host}}/edit-status/3 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nomor_meja":23,
    "status":"tidak_tersedia"
}


###DELETE MEJA BY NOMOR MEJA --NOTE
DELETE  {{host}}/delete/2 HTTP/1.1
Authorization: Bearer {{token}}

