@host = http://localhost:8080/menu
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZF91c2VyIjoxLCJ1c2VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg3NjE5OTcsImV4cCI6MTY4MDQ0MDc1OTYyMn0.qxyBz12lMciwixoIKXa0H8Zhd3hZOlJ4ON-yinmX9YI


### GET MENU
GET  {{host}}/get HTTP/1.1
Authorization: Bearer {{token}}

### GET MENU BY ID
GET  {{host}}/get/3 HTTP/1.1
Authorization: Bearer {{token}}

### FIND MENU BY KEYWORD 
GET {{host}}/nama-menu?q=ikan HTTP/1.1
Authorization: Bearer {{token}}

### FIND MENU BY JENIS
GET {{host}}/jenis-menu/makanan HTTP/1.1
Authorization: Bearer {{token}}

###DELETE MENU --NOTE
DELETE  {{host}}/delete/3 HTTP/1.1
Authorization: Bearer {{token}}

