# GET MENU
GET  http://localhost:8080/menu/get HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJ1c2VybmFtZSI6IlN5ZWxhIiwiZW1haWwiOiJzeWVsYUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg1MjEwMzgsImV4cCI6MTY4MDE5OTU1OTg1MH0.xFcixalkEZQdRextFrcIACc99hXOZv2nJMtbH1DP0qk

### GET MENU BY ID
GET  http://localhost:8080/menu/get/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJ1c2VybmFtZSI6IlN5ZWxhIiwiZW1haWwiOiJzeWVsYUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg1MjEwMzgsImV4cCI6MTY4MDE5OTU1OTg1MH0.xFcixalkEZQdRextFrcIACc99hXOZv2nJMtbH1DP0qk

### FIND MENU BY KEYWORD 
GET http://localhost:8080/menu/nama-menu?q=ikan HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJ1c2VybmFtZSI6IlN5ZWxhIiwiZW1haWwiOiJzeWVsYUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg1MjEwMzgsImV4cCI6MTY4MDE5OTU1OTg1MH0.xFcixalkEZQdRextFrcIACc99hXOZv2nJMtbH1DP0qk

### FIND MENU BY JENIS
GET http://localhost:8080/menu/jenis-menu/makanan HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJ1c2VybmFtZSI6IlN5ZWxhIiwiZW1haWwiOiJzeWVsYUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg1MjEwMzgsImV4cCI6MTY4MDE5OTU1OTg1MH0.xFcixalkEZQdRextFrcIACc99hXOZv2nJMtbH1DP0qk

###DELETE MENU --NOTE
DELETE  http://localhost:8080/menu/delete/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJ1c2VybmFtZSI6IlN5ZWxhIiwiZW1haWwiOiJzeWVsYUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg1MjEwMzgsImV4cCI6MTY4MDE5OTU1OTg1MH0.xFcixalkEZQdRextFrcIACc99hXOZv2nJMtbH1DP0qk

