@host = http://localhost:8080/transaksi
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZF91c2VyIjoxLCJ1c2VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg3NjE5OTcsImV4cCI6MTY4MDQ0MDc1OTYyMn0.qxyBz12lMciwixoIKXa0H8Zhd3hZOlJ4ON-yinmX9YI

### INSERT TRANSAKSI --NOTE
POST {{host}}/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id_meja": 3,
    "nama_pelanggan": "yanti",
    "detail_transaksi":[
        { 
            "id_menu": "2",
            "qty" : 3
        },
        { 
            "id_menu": "2",
            "qty" : 10
        }
    ]
}

### EDIT TRANSAKSI
PUT  {{host}}/edit/10 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id_meja": 4,
    "nama_pelanggan": "yanti",
    "detail_transaksi":[
        { 
            "id_menu": "2",
            "qty" : 5
        },
        { 
            "id_menu": "2",
            "qty" : 10
        }
    ]
}

### BAYAR
PUT  {{host}}/pay/22 HTTP/1.1
Authorization: Bearer {{token}}

### DELETE
DELETE {{host}}/delete/21
Authorization: Bearer {{token}}

### TRANSAKSI BY KASIR
GET {{host}}/transaksi-kasir HTTP/1.1
Authorization: Bearer {{token}}


### GET ALL TRANSAKSI
GET {{host}}/get HTTP/1.1
Authorization: Bearer {{token}}

### GET LIST MENU
GET {{host}}/list-menu HTTP/1.1
Authorization: Bearer {{token}}

### GET LIST MENU
GET {{host}}/transaksi-harian HTTP/1.1
Authorization: Bearer {{token}}