
@host = http://localhost:8080/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZF91c2VyIjo1LCJ1c2VybmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg5MDE0MzEsImV4cCI6MTY4MDU4MDMzMjcxOH0.rtGhL1Fv6M9osqwKLDHnEnKUQlPqk11kXW7RLC18kFw


### Token manager
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZF91c2VyIjo3LCJ1c2VybmFtZSI6Im1hbmFnZXIiLCJlbWFpbCI6Im1hbmFnZXJAZXhhbXBsZS5jb20iLCJyb2xlIjoibWFuYWdlciJ9LCJpYXQiOjE2Nzg5MDE2MzYsImV4cCI6MTY4MDU4MDUzODY2Mn0.a2JFT5uploOeE1zuqOttW4lq3BQpfGVg-pR1vSJBbec

### GET USER
GET  {{host}}/get HTTP/1.1
Authorization: Bearer {{token}}

### GET BY ID
GET  {{host}}/get/4 HTTP/1.1
Authorization: Bearer {{token}}


### INSERT USER
POST {{host}}/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama_user": "bersamasama", 
    "role": "kasir",
    "username": "bersamasama", 
    "email": "bersamasama@gmail.com", 
    "password": "Password123#", 
    "confPassword": "Password123#"
}

### FIND USER BY KEYWORD
GET {{host}}/search-user?q=@example.com HTTP/1.1
Authorization: Bearer {{token}}

### EDIT USER
PUT {{host}}/edit/2 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nama_user": "vigos",
    "role": "kasir",
    "username": "vigos",
    "email": "vigookta@gmail.com"
}

### EDIT USER ROLE
PUT {{host}}/update-role/7 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "role": "manager"
}


###DELETE USER
DELETE  {{host}}/delete/12 HTTP/1.1
Authorization: Bearer {{token}}

